---
- name: Install Kerbrute
  ansible.builtin.get_url:
    url: https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64
    dest: /usr/local/bin/kerbrute
    mode: '755'
    checksum: sha256:710a9d2653c8bd3689e451778dab9daec0de4c4c75f900788ccf23ef254b122a
  tags:
    - kerbrute
