#!/usr/bin/env bash

NEO4J_BIN=/usr/share/neo4j/bin
SCRIPT_NAME="$(basename "$0")"
SCRIPT_PATH=""${NEO4J_BIN}"/"${SCRIPT_NAME}""

[ -r /etc/default/neo4j ] && . /etc/default/neo4j

NEO4J_HOME="${NEO4J_HOME:-/var/lib/neo4j}" NEO4J_CONF="${NEO4J_CONF:-/etc/neo4j}" JAVA_HOME=/etc/alternatives/jre_11 exec "${SCRIPT_PATH}" "$@"
